//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplicacion_web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class documento
    {
        public int id_doc { get; set; }
        public int id_tipo_doc { get; set; }
        public string Cedula { get; set; }
        public string Nom_doc_encon { get; set; }
        public string Ape_doc_encon { get; set; }
        public string Ced_per_encon { get; set; }
        public string Nom_pers_encon { get; set; }
        public string Ape_perso_encon { get; set; }
        public string Nmr_contacto { get; set; }
        public string Email_contacto { get; set; }
        public string Lugar_encon { get; set; }
        public Nullable<System.DateTime> Fecha_registro { get; set; }
    }
}
